/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as NewsRouteImport } from './routes/news'
import { Route as StudentLifeRouteImport } from './routes/student-life'
import { Route as AcademicsIndexRouteImport } from './routes/academics.index'
import { Route as AcademicsClassRouteImport } from './routes/academics.$class'
import { Route as AcademicsProgrammeRouteImport } from './routes/academics.$programme'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLifeRoute = StudentLifeRouteImport.update({
  id: '/student-life',
  path: '/student-life',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsIndexRoute = AcademicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademicsRoute,
} as any)
const AcademicsClassRoute = AcademicsClassRouteImport.update({
  id: '/$class',
  path: '/$class',
  getParentRoute: () => AcademicsRoute,
} as any)
const AcademicsProgrammeRoute = AcademicsProgrammeRouteImport.update({
  id: '/$programme',
  path: '/$programme',
  getParentRoute: () => AcademicsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/fees': typeof FeesRoute
  '/news': typeof NewsRoute
  '/student-life': typeof StudentLifeRoute
  '/academics/$class': typeof AcademicsClassRoute
  '/academics/$programme': typeof AcademicsProgrammeRoute
  '/academics/': typeof AcademicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/fees': typeof FeesRoute
  '/news': typeof NewsRoute
  '/student-life': typeof StudentLifeRoute
  '/academics/$class': typeof AcademicsClassRoute
  '/academics/$programme': typeof AcademicsProgrammeRoute
  '/academics': typeof AcademicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/fees': typeof FeesRoute
  '/news': typeof NewsRoute
  '/student-life': typeof StudentLifeRoute
  '/academics/$class': typeof AcademicsClassRoute
  '/academics/$programme': typeof AcademicsProgrammeRoute
  '/academics/': typeof AcademicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/fees'
    | '/news'
    | '/student-life'
    | '/academics/$class'
    | '/academics/$programme'
    | '/academics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/fees'
    | '/news'
    | '/student-life'
    | '/academics/$class'
    | '/academics/$programme'
    | '/academics'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/fees'
    | '/news'
    | '/student-life'
    | '/academics/$class'
    | '/academics/$programme'
    | '/academics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRouteWithChildren
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  FeesRoute: typeof FeesRoute
  NewsRoute: typeof NewsRoute
  StudentLifeRoute: typeof StudentLifeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life': {
      id: '/student-life'
      path: '/student-life'
      fullPath: '/student-life'
      preLoaderRoute: typeof StudentLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/': {
      id: '/academics/'
      path: '/'
      fullPath: '/academics/'
      preLoaderRoute: typeof AcademicsIndexRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/academics/$class': {
      id: '/academics/$class'
      path: '/$class'
      fullPath: '/academics/$class'
      preLoaderRoute: typeof AcademicsClassRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/academics/$programme': {
      id: '/academics/$programme'
      path: '/$programme'
      fullPath: '/academics/$programme'
      preLoaderRoute: typeof AcademicsProgrammeRouteImport
      parentRoute: typeof AcademicsRoute
    }
  }
}

interface AcademicsRouteChildren {
  AcademicsClassRoute: typeof AcademicsClassRoute
  AcademicsProgrammeRoute: typeof AcademicsProgrammeRoute
  AcademicsIndexRoute: typeof AcademicsIndexRoute
}

const AcademicsRouteChildren: AcademicsRouteChildren = {
  AcademicsClassRoute: AcademicsClassRoute,
  AcademicsProgrammeRoute: AcademicsProgrammeRoute,
  AcademicsIndexRoute: AcademicsIndexRoute,
}

const AcademicsRouteWithChildren = AcademicsRoute._addFileChildren(
  AcademicsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRouteWithChildren,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  FeesRoute: FeesRoute,
  NewsRoute: NewsRoute,
  StudentLifeRoute: StudentLifeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
